# Build
# -------------------------------------

language: node_js
node_js:
    - "8"

# Deployment
# -------------------------------------

deploy:
    provider: npm
    on:
        tags: true
        node: "8"
    api_key:
        secure: ""
    email: "lsphillips.mail@gmail.com"
