# Build
# -------------------------------------

language: node_js
node_js:
  - "10"

# Deployment
# -------------------------------------

deploy:
  provider: npm
  on:
    tags: true
    node: "10"
  api_key:
    secure: "KtqB7U2tN8V6/AGsKX7XKV/0iOs81YcCkhJkatCRXYYtn5O41K8xahK13s1wKGJ8KnHDshJx2VYdTB/VXMmKHNs0gvE3nTDIfpyJr9l7hi/PF7t0AswGwMJWjlw7rKt9ic5rHRkiGGRB7CHnjfV0PvoUfr5VKLC+T8Vk5BIJ9GxIp3Ze6AgPxQi3PqFq/d/sp+QTmp2rzmw3ggNXumACwPA/14CB4FyISoqEtWikhmrGlRR0UqVzKTzqHk7cBjmM97R4vC15d4NFnGzVgCZ6EPxjCILwoinxhPrDelQHO55aamGJsd7jMPwXJl5fXLQh3vSVbxn57tgtenkTw8mV3I13o4tW0rMPffpWBamfDV17+XLKR6ZGK3RIebYRGCnmBssr/iC3VmvFqxCMXMyyYYP9SKxV3uEby490O/RaEduIGWQWyuqCzu4Vda6KCk1hUMEzvUFKvZAsh+MKVsoq7RnTPIrranPahkuvhH8YgCltlseDNpYjtnZIF0Fwlcf0g4pLYaJmrv0k9H9lnnQf8y7jwu49Ti/ZdkezZ2m3Uk/3bCX3USPLGiHArRxXK+PiCx/vrIoGOV3+Pue2x+wPKtNFdYAV9JrwA4DBvNBfKuO0OkvbWbh+Oq6qa8jjzhksP/GfNINzFrbRKVBzO7z9A/nWURdIdjOXeWoTlP1sck4="
  email: "lsphillips.mail@gmail.com"
